name: deploy_frontend
# Deploys when push in made from frontend folder

on:
    push:
        branches: [ main ]
        paths: 
        - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name getresumecounterfinal --auth-mode key -d '$web' -s frontend/
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "azureresume" --name "azureresumendmausehund" --resource-group "getresumecounterfinal"

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()